from setuptools import setup, find_packages

setup(
    name="pdf-blog",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "crewai==0.105.0",
        "crewai-tools==0.37.0",
        "langchain==0.3.20",
        "openai==1.65.5",
        "python-dotenv==1.0.1",
        "PyPDF2==3.0.1",
        "pdfplumber==0.11.5",
        "fastapi==0.115.11",
        "uvicorn==0.34.0",
        "python-multipart==0.0.20",
        "starlette==0.45.3",
        "pytest==8.3.5",
        "pytest-cov==6.0.0",
        "coverage==7.6.12",
        "black==24.8.0",
        "isort==5.13.2",
        "flake8==7.0.0",
        "anyio==4.2.0",
        "httpx==0.27.0",
    ],
    python_requires=">=3.8",
    author="Erick Loyola",
    author_email="gamaerick027@gmail.com.com",
    description="Sistema de processamento de PDFs e geração de posts de blog",
    keywords="pdf, blog, ai, nlp, crewai",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)